---
- hosts: master
  name: Management server configuration
  become: true
  gather_facts: true
  tasks:
  - name: Install python 
    raw: test -e /usr/bin/python || (sudo apt -y update && sudo apt install -y python-minimal)   
  vars_files:
  - ./projvars.yml
  - ./prerequisite.yml
  - ./provisionvars.yml
  roles:
  - { role: docker}
  - { role: kubernetes-master}
  remote_user: centos

- hosts: ks-nodes 
  name: Nodes configuration
  vars_files:
  - ./projvars.yml
  - ./prerequisite.yml
  - ./provisionvars.yml
  - ./{{ cloud }}.yml
  remote_user: centos

  ignore_errors: true
  become: true
  gather_facts: true
  roles:
  - { role: docker}
  - { role: kubernetes-node}  
  tasks:
  - name: Run the plays
    include: "{{proj}}.yml"

