---
- name: update hosts file
  hosts: all
  become: true
  gather_facts: false
  remote_user: ubuntu
  tasks:
   - name: Install python 
     raw: test -e /usr/bin/python || (sudo apt -y update && sudo apt install -y python-minimal)   
   - name: update hosts
     lineinfile:
       dest: /etc/hosts
       regexp: '.*{{ item }}$'
       line: "{{ hostvars[item].public_ip }} {{item}}"
       state: present
     with_items: "{{ groups.all }}"

- hosts: master
  name: Management server configuration
  become: true
  gather_facts: true
  tasks:
  - name: Install python 
    raw: test -e /usr/bin/python || (sudo apt -y update && sudo apt install -y python-minimal)   
  vars_files:
  - ./projvars.yml
  - ./prerequisite.yml
  - ./provisionvars.yml
  roles:
  - { role: kube-master}
#  - { role: dashboard-setup }
  remote_user: ubuntu

- hosts: nodes
  name: Nodes configuration
  vars_files:
  - ./projvars.yml
  - ./prerequisite.yml
  - ./provisionvars.yml
  - ./{{ cloud }}.yml
  remote_user: ubuntu
  ignore_errors: true
  become: true
  gather_facts: true
  roles:
  - { role: kube-node}  

- hosts: master
  name: deploy nginx container
  become: true
  remote_user: ubuntu
  tasks:
    - name: Copy the nginx yaml file
      copy:
        src: kube-nginx.yaml
        dest: /root/

    - name: Create container
      shell: kubectl create -f /root/kube-nginx.yaml
  

